# Generated by Django 4.2.1 on 2023-05-24 18:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first', models.CharField()),
                ('last', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField()),
                ('shortName', models.CharField()),
                ('longName', models.CharField()),
                ('address1', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('country', models.CharField()),
                ('phone', models.CharField()),
                ('website', models.CharField()),
                ('industry', models.CharField()),
                ('sector', models.CharField()),
                ('longBuisnessSummary', models.TextField()),
                ('auditRisk', models.IntegerField()),
                ('boardRisk', models.IntegerField()),
                ('compensationRisk', models.IntegerField()),
                ('shareHolderRightsRisk', models.IntegerField()),
                ('overallRisk', models.IntegerField()),
                ('open', models.IntegerField()),
                ('dayLow', models.IntegerField()),
                ('dayHigh', models.IntegerField()),
                ('currentPrice', models.IntegerField()),
                ('beta', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('averageVolume', models.IntegerField()),
                ('targetMeanPrice', models.IntegerField()),
                ('dividendRate', models.IntegerField(null=True)),
                ('dividendYield', models.IntegerField(null=True)),
                ('forwardPE', models.IntegerField()),
                ('regularMarketPreviousClose', models.IntegerField()),
                ('regularMarketOpen', models.IntegerField()),
                ('regularMarketDayLow', models.IntegerField()),
                ('regularMarketDayHigh', models.IntegerField()),
                ('marketCap', models.IntegerField()),
                ('fiftyTwoWeekHigh', models.IntegerField()),
                ('fiftyTwoWeekLow', models.IntegerField()),
                ('currency', models.CharField()),
                ('recommendationMean', models.IntegerField()),
                ('recommendationKey', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(null=True)),
                ('validRanges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, size=None)),
                ('Open', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, size=None)),
                ('Close', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, size=None)),
                ('High', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, size=None)),
                ('Low', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, size=None)),
                ('Volume', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField()),
                ('shortName', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
