# Generated by Django 4.2.1 on 2023-05-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='useracct_ptr',
        ),
        migrations.DeleteModel(
            name='UserAcctManager',
        ),
        migrations.RemoveField(
            model_name='useracct',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='appUser',
        ),
    ]
