# Generated by Django 4.2.1 on 2023-05-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_company_symbol_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Symbol',
        ),
        migrations.AlterField(
            model_name='company',
            name='Name',
            field=models.CharField(max_length=10),
        ),
    ]
