# Generated by Django 4.2.1 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_company_symbol_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
