# Generated by Django 4.2.1 on 2023-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_company_symbol_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Name',
            field=models.CharField(),
        ),
    ]
