# Generated by Django 4.2.1 on 2023-05-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='ticker',
        ),
        migrations.AddField(
            model_name='company',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.history'),
        ),
    ]
