# Generated by Django 4.2.1 on 2023-05-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_remove_company_history_history_ticker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='dividends',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='open',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='splits',
            new_name='Open',
        ),
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
    ]
