# Generated by Django 4.2.1 on 2023-05-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_rename_close_history_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='ticker',
            new_name='Company_id',
        ),
    ]
