# Generated by Django 4.2.1 on 2023-05-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_rename_ticker_history_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField()),
                ('shortName', models.CharField()),
                ('longName', models.CharField()),
                ('address1', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('country', models.CharField()),
                ('phone', models.CharField()),
                ('website', models.CharField()),
                ('sector', models.CharField()),
                ('logBuisnessSummary', models.CharField()),
                ('overallRisk', models.IntegerField()),
                ('open', models.IntegerField()),
                ('dayLow', models.IntegerField()),
                ('dayHigh', models.IntegerField()),
                ('regularMarketPreviousClose', models.IntegerField()),
                ('regularMarketOpen', models.IntegerField()),
                ('regularMarketDayLow', models.IntegerField()),
                ('regularMarketDayHigh', models.IntegerField()),
                ('marketCap', models.IntegerField()),
                ('fiftyTwoWeekHigh', models.IntegerField()),
                ('fiftyTwoWeekLow', models.IntegerField()),
                ('currency', models.CharField()),
            ],
        ),
    ]
