# Generated by Django 4.2.1 on 2023-05-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='stocks.company'),
        ),
    ]
