# Generated by Django 4.2.1 on 2023-05-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_companyinfo_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_id',
            new_name='Company_id',
        ),
    ]
