# Generated by Django 4.2.1 on 2023-05-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_rename_company_id_companyinfo_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='logBuisnessSummary',
            new_name='longBuisnessSummary',
        ),
    ]
