# Generated by Django 4.2.1 on 2023-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_rename_logbuisnesssummary_companyinfo_longbuisnesssummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='Company_id',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='longBuisnessSummary',
            field=models.TextField(),
        ),
    ]
